# Relevant GHA docs links:
# https://docs.github.com/en/actions/using-jobs/running-jobs-in-a-container
# https://docs.github.com/en/packages/managing-github-packages-using-github-actions-workflows/publishing-and-installing-a-package-with-github-actions#upgrading-a-workflow-that-accesses-ghcrio

name: Build PyPI package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: '${{ github.workflow }}-${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  build-halide:
    name: Build Halide

    runs-on: ubuntu-latest

    container:
      image: ghcr.io/halide/manylinux2014_x86_64-llvm:14.0.6
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v3

      - name: Configure Halide
        run: >
          cmake -G Ninja -S . -B build
          -DCMAKE_BUILD_TYPE=Release
          -DCMAKE_INSTALL_PREFIX=$PWD/local
          -DWITH_DOCS=NO
          -DWITH_PYTHON_BINDINGS=NO
          -DWITH_TESTS=NO
          -DWITH_TUTORIALS=NO
          -DWITH_UTILS=NO

      - name: Build Halide
        run: cmake --build build --target install

      - name: Tar Halide binaries
        run: tar cvf halide-bin.tar ./local

      - name: Upload Halide binaries
        uses: actions/upload-artifact@v3
        with:
          name: halide-bin
          path: halide-bin.tar

  build-wheels:
    name: Build wheels (${{ matrix.python }})

    needs: build-halide

    runs-on: ubuntu-latest

    container:
      image: ghcr.io/halide/manylinux2014_x86_64-llvm:14.0.6
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
      env:
        PYTHON: /opt/python/${{ matrix.python }}/bin/python

    strategy:
      matrix:
        python:
          # The following list is exhaustive, but the commented ABIs are
          # unsupported. (<3.8 or PyPy)
          # - cp36-cp36m
          # - cp37-cp37m
          - cp38-cp38
          - cp39-cp39
          - cp310-cp310
          # - cp311-cp311  # unreleased
          # - pp37-pypy37_pp73
          # - pp38-pypy38_pp73
          # - pp39-pypy39_pp73

    steps:
      - uses: actions/checkout@v3

      - name: Download Halide binaries
        uses: actions/download-artifact@v3
        with:
          name: halide-bin

      - name: Untar Halide binaries
        run: tar xvf halide-bin.tar

      - name: Build wheels
        run: |
          export CMAKE_PREFIX_PATH=$GITHUB_WORKSPACE/local
          $PYTHON -m build python_bindings

      - name: Upload wheel
        uses: actions/upload-artifact@v3
        with:
          name: packages
          path: python_bindings/dist

