name: Build PyPI package
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
concurrency:
  group: '${{ github.workflow }}-${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true
jobs:
  build-binary-dependencies:
    name: Build Halide
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    container: ghcr.io/halide/manylinux2014_x86_64-llvm:14.0.6
    steps:
      - uses: actions/checkout@v3
      - name: Install Ninja
        run: |
          curl -LO https://github.com/ninja-build/ninja/releases/download/v1.11.0/ninja-linux.zip
          unzip -o ninja-linux.zip -d /usr/local/bin
          rm -f ninja-linux.zip
      - name: Configure Halide
        run: >
          cmake
          -G Ninja
          -S .
          -B build
          -DCMAKE_BUILD_TYPE=Release
          -DCMAKE_INSTALL_PREFIX=$PWD/local
          -DWITH_DOCS=NO
          -DWITH_PYTHON_BINDINGS=NO
          -DWITH_TESTS=NO
          -DWITH_TUTORIALS=NO
          -DWITH_UTILS=NO
      - name: Build Halide
        run: cmake --build build --target install
      - name: Upload binary dependencies
        uses: actions/upload-artifact@v3
        with:
          name: binary-dependencies
          path: local
  build-wheels:
    name: Build wheels (${{ matrix.python }})
    needs: build-binary-dependencies
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    container:
      image: ghcr.io/halide/manylinux2014_x86_64-llvm:14.0.6
      env:
        PYTHON: /opt/python/${{ matrix.python }}/bin/python
    strategy:
      matrix:
        python:
          # The following list is exhaustive, but the commented ABIs are
          # unsupported. (<3.8 or PyPy)
          # - cp36-cp36m
          # - cp37-cp37m
          - cp38-cp38
          - cp39-cp39
          - cp310-cp310
          # - cp311-cp311  # unreleased
          # - pp37-pypy37_pp73
          # - pp38-pypy38_pp73
          # - pp39-pypy39_pp73
    steps:
      - uses: actions/checkout@v3
      - name: Download binary dependencies
        uses: actions/download-artifact@v3
        with:
          name: binary-dependencies
      - name: Build wheels
        run: $PYTHON -m build python_bindings
        env:
          CMAKE_PREFIX_PATH: ${{ github.workspace }}/local
      - name: Upload wheel
        uses: actions/upload-artifact@v3
        with:
          name: packages
          path: python_bindings/dist
